name: Build and Deploy Website

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    env:
      GONER_URL: "https://github.com/TheVessels/GonerEngine/archive/refs/heads/gaster.zip"
      GONER_PATH: "GonerEngine-gaster"
      GODOT_EXEC: "./Godot_v4.7-stable_linux.x86_64"
      GODOT_URL: "https://downloads.godotengine.org/?version=4.7&flavor=stable&slug=linux.x86_64.zip&platform=linux.64"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download GonerEngine
        run: |
          curl -L "$GONER_URL" > repo.zip
          unzip repo.zip
          mv "$GONER_PATH" GonerEngine
          rm repo.zip
      - name: Download Godot
        run: |
          curl -L "$GODOT_URL" > godot.zip
          unzip godot.zip
          rm godot.zip
      - name: Generate reference XML
        run: |
          "$GODOT_EXEC" --headless --path GonerEngine --import
          "$GODOT_EXEC" --headless --path GonerEngine --doctool $PWD/src/reference --gdscript-docs res://scripts/classes
      - name: Install dependencies
        run: |
          npm i
      - name: Build website (Vitepress)
        run: |
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./src/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5


